#ifndef WORLD_CONSTANTS_H_INCLUDED
#define WORLD_CONSTANTS_H_INCLUDED

constexpr int   CHUNK_SIZE = 16,
                CHUNK_VOLUME = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;

#endif // WORLD_CONSTANTS_H_INCLUDED
